export const constants = {
  "letters": [
    { "key": "A" },
    { "key": "B" },
    { "key": "C" },
    { "key": "D" },
    { "key": "E" },
    { "key": "F" },
    { "key": "G" },
    { "key": "H" },
    { "key": "I" },
    { "key": "J" },
    { "key": "K" },
    { "key": "L" },
    { "key": "M" },
    { "key": "N" },
    { "key": "O" },
    { "key": "P" },
    { "key": "Q" },
    { "key": "R" },
    { "key": "S" },
    { "key": "T" },
    { "key": "↵" },
    { "key": "U" },
    { "key": "V" },
    { "key": "W" },
    { "key": "X" },
    { "key": "Y" },
    { "key": "Z" },
    { "key": "⌫" }
  ],
  "solutions": [
    { "id": 1, "word": "happy" },
    { "id": 2, "word": "whale" },
    { "id": 3, "word": "money" },
    { "id": 4, "word": "drive" },
    { "id": 5, "word": "relax" },
    { "id": 6, "word": "times" },
    { "id": 7, "word": "train" },
    { "id": 8, "word": "cores" },
    { "id": 9, "word": "pours" },
    { "id": 10, "word": "blame" },
    { "id": 11, "word": "banks" },
    { "id": 12, "word": "phone" },
    { "id": 13, "word": "bling" },
    { "id": 14, "word": "coins" },
    { "id": 15, "word": "hello" },
    { "id": 16, "word": "ninja" },
    { "id": 17, "word": "pools" },
    { "id": 18, "word": "spade" }
  ]
}
